name: "terraria"

services:
  installer:
    image: ghcr.io/notruri/debian-base:latest
    working_dir: /mnt/terraria
    entrypoint: /install.sh
    # entrypoint: /bin/bash
    # tty: true
    # stdin_open: true
    volumes:
      - ./install.sh:/install.sh
      - data:/mnt/terraria

  server:
    image: debian:bookworm-slim
    working_dir: /mnt/terraria
    entrypoint: /entrypoint.sh
    # entrypoint: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - data:/mnt/terraria
      - worlds:/mnt/terraria/.local/share/Terraria/Worlds
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '4GB'
        reservations:
          cpus: '2.0'
          memory: '4GB'
    environment:
      HOME: /mnt/terraria
      # BIN: "TerrariaServer" # 32-bit
      BIN: "TerrariaServer.bin.x86_64"
      PARAMS: "-autocreate 2 -world /mnt/terraria/.local/share/Terraria/Worlds/world.wld -ip 0.0.0.0 -port 7777 -noupnp -players 16"

volumes:
  data:
  worlds:
